# fly.toml app configuration file generated for actix-test on 2023-09-23T14:54:24+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rusty-sandwiches"
primary_region = "lhr"

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
